{
  "hash": "85ce8b3ffd1c544569feedba7aef3430",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Consumption of Alcohol in Russia\"\nauthor: \"Gloria Sunderland\"\ndate: \"2024-12-12\"\ncategories: [data analysis]\nimage: \"image.jpg\"\n---\n\n\nData Source: <https://www.kaggle.com/datasets/scibearia/consumption-of-alcohol-in-russia-2017-2023>\n\n------------------------------------------------------------------------\n\nData Description: Data set includes alcohol consumption information across the years 2017-2023 for different alcohol types including wine, beer, vodka, sparkling wine, brandy, cider, liqueurs.\n\n------------------------------------------------------------------------\n\n**Research Questions**\n\n1.  How has the consumption of different types of alcohol changed over time in Russia?\n2.  Can the consumption of one type of alcohol (ex. vodka) predict the consumption of other types (ex. beer, wine, or total alcohol)?\n\n\n\n\n\n# Research Question 1\n\n### Data visualization\n\n\n::: {.cell warnings='false'}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n**Figure 1**. Line plot of trends in Alcohol Consumption in Russia (2017–2023) across all alcohol types show that beer consumption remains consistently high with only a slight upward trend over time, with the other alcohol types appearing stable across time.\n\n---\n\n\n::: {.cell warnings='false'}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n**Figure 2.** Trends in Alcohol Consumption in Russia (2017–2023), excluding beer, highlight a very slight increase in the consumption of vodka, wine, and liqueuers. Other alcohol types, such as sparkling wine and cider, show minimal changes.\n\n---\n\n# Research Question 2\n\n### Data Visualization\n\n\n::: {.cell warnings='false'}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n**Figure 3.** Scatter plot showing relationship between vodka and beer consumption. A positive trend here suggests that higher consumption of vodka is associated with higher beer consumption. This suggests a relationship between the consumption of different types of alcohol. However, statistical analysis is needed to fully understand the nature of this relationship.\n\n---\n\n### Correlation Matrix\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n**Figure 4.** Correlation matrix showing the relationships between different alcohol beverages. There are strong positive correlations between wine and sparkling wine (0.82), brandy and sparkling wine (0.87), and vodka and brandy (0.76), suggesting that higher consumption of one is associated with higher consumption of the other. Moderate correlations are also present between beer and other alcohol types, such as vodka (0.68).\n\n---\n\n### Statistical Analysis\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Total.alcohol.consumption..in.liters.of.pure.alcohol.per.capita. ~ \n    Vodka + Beer + Wine, data = Russia_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.10772 -0.13759  0.01251  0.14529  0.73872 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.0278246  0.0269928   1.031    0.303    \nVodka       0.4724764  0.0053965  87.552   <2e-16 ***\nBeer        0.0559735  0.0007427  75.361   <2e-16 ***\nWine        0.3270103  0.0078312  41.757   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.224 on 591 degrees of freedom\nMultiple R-squared:  0.9917,\tAdjusted R-squared:  0.9917 \nF-statistic: 2.353e+04 on 3 and 591 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n**Model 1.** Linear regression model predicting total alcohol consumption based on vodka, beer, and wine consumption. The results indicate that vodka consumption has the strongest positive relationship with total alcohol consumption (coefficient = 0.47), followed by wine (0.33) and beer (0.056). The model explains 99.17% of the variance in total alcohol consumption (R-squared = 0.9917), demonstrating an excellent fit. All predictors are statistically significant, highlighting their importance in driving total alcohol consumption.\n\n---\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}