{
  "hash": "6c84c47e14726700579c2b666fd43983",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Student Depression Dataset\"\nauthor: \"Gloria Sunderland\"\ndate: \"2024-12-11\"\ncategories: [data analysis]\n---\n\n\n# Student Depression Dataset\n\nData Source: [[https://www.kaggle.com/datasets/hopesb/student-depression-dataset/data]{.underline}](https://www.kaggle.com/datasets/hopesb/student-depression-dataset/data)\n\n------------------------------------------------------------------------\n\nData Description/ Variables of Interest:\n\n-   ID: Unique Student Identifier\n\n-   Age: Age of student\n\n-   Gender: Gender of student (Male, Female)\n\n-   CGPA: Grade Point Average, or measure of Academic Success\n\n-   Sleep Duration: Average daily sleep duration\n\n-   Academic Pressure: Scale from 1 (least pressure) to 5 (most pressure)\n\n-   Study Satisfaction: Scale from 1 (least satisfied) to 5 (most satisfied)\n\n-   Depression: Does the student feel depressed (Yes/No)\n\n------------------------------------------------------------------------\n\n**Research Question**: How do sleep duration and academic pressure affect CGPA and study satisfaction among students?\n\n------------------------------------------------------------------------\n\n# 1. Preparing the data & Visualizing the variables\n\n\n\n\n\n\n::: {.cell warnings='false'}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n**Figure 1**. Box plot showing the distribution of CGPA across sleep duration categories. There is no clear relationship, as the median CGPA stays relatively consistent across all sleep duration groups. This suggests that sleep duration may not have a strong impact on CGPA.\n\n\n::: {.cell warnings='false'}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n**Figure 2**. Scatter plot showing relationship between academic pressure and CGPA. There appears to be a slight trend, with higher academic pressure associated with slightly lower CGPA, although the pattern is not strong.\n\n------------------------------------------------------------------------\n\n# 2. Statistical Analysis\n\n### Correlation Matrix\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n**Figure 3.** Correlation matrix showing relationship between variables of interest: Academic Pressure, CGPA, Study Satisfaction, and Sleep Duration. The values range from -1 to 1 (with 0 indicating no correlation). The matrix shows weak correlations among the variables. Academic Pressure stands out as it has a slight negative correlation with Study Satisfaction (-0.11) and CGPA (-0.02).\n\n------------------------------------------------------------------------\n\n### Linear Regression\n\n**Model 1**. Linear regression to predict CGPA from Sleep duration and Academic pressure.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = CGPA ~ Sleep.Duration + Academic.Pressure, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-7.7639 -1.3519  0.1131  1.2642  2.4388 \n\nCoefficients:\n                                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                      7.763893   0.027312 284.266  < 2e-16 ***\nSleep.Duration7-8 hours         -0.002731   0.025375  -0.108 0.914276    \nSleep.DurationLess than 5 hours -0.046314   0.024703  -1.875 0.060823 .  \nSleep.DurationMore than 8 hours -0.083029   0.026598  -3.122 0.001800 ** \nSleep.DurationOthers            -0.092559   0.347012  -0.267 0.789677    \nAcademic.Pressure               -0.023930   0.006378  -3.752 0.000176 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.47 on 27892 degrees of freedom\nMultiple R-squared:  0.0009943,\tAdjusted R-squared:  0.0008152 \nF-statistic: 5.552 on 5 and 27892 DF,  p-value: 4.078e-05\n```\n\n\n:::\n:::\n\n\nThis linear regression model looks at the relationship between CGPA, Sleep Duration, and Academic Pressure.\n\nThe intercept suggests that students with the reference Sleep Duration (5-6 hours) and no Academic Pressure have an average CGPA of 7.76. Sleep Duration categories mostly do not significantly impact CGPA, except for 'More than 8 hours,' which is associated with a significant decrease of 0.083 in CGPA (p = 0.0018).\n\nAcademic Pressure shows a small but significant negative effect on CGPA, with every one-unit increase associated with a decrease of 0.024 (p = 0.0002).\n\nImportantly, the model explains only less than 0.1% of the variation in CGPA (R-squared = 0.0009943), meaning that other variables not included in the model play a more substantial role in predicting CGPA.\n\n------------------------------------------------------------------------\n\n**Model 2**. Linear regression to predict Study Satisfaction from Sleep duration and Academic pressure\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Study.Satisfaction ~ Sleep.Duration + Academic.Pressure, \n    data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.3075 -0.9804  0.0365  1.0545  2.2726 \n\nCoefficients:\n                                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                      3.290638   0.025132 130.935   <2e-16 ***\nSleep.Duration7-8 hours         -0.009593   0.023349  -0.411    0.681    \nSleep.DurationLess than 5 hours -0.018026   0.022731  -0.793    0.428    \nSleep.DurationMore than 8 hours  0.016830   0.024475   0.688    0.492    \nSleep.DurationOthers             0.165757   0.319311   0.519    0.604    \nAcademic.Pressure               -0.109037   0.005869 -18.578   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.353 on 27892 degrees of freedom\nMultiple R-squared:  0.01244,\tAdjusted R-squared:  0.01226 \nF-statistic: 70.26 on 5 and 27892 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThis linear regression model looks at the relationship between Study Satisfaction, Sleep Duration, and Academic Pressure. The intercept indicates that students with the reference Sleep Duration (5-6 hours) and no Academic Pressure have an average Study Satisfaction score of 3.29.\n\nSleep Duration categories do not significantly affect Study Satisfaction, as none of the categories show significant p-values. Academic Pressure, however, has a substantial and significant negative effect on Study Satisfaction, with each one-unit increase in Academic Pressure associated with a decrease of 0.109 in Study Satisfaction (p \\< 2e-16).\n\nThis model explains only 1.2% of the variation in Study Satisfaction (R-squared = 0.01244), meaning that other factors not included in the model contribute significantly to variations in Study Satisfaction.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}